// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iopdbcvykxloerwinrzd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlvcGRiY3Z5a3hsb2Vyd2lucnpkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0ODA4MjMsImV4cCI6MjA2MDA1NjgyM30.PeXux0lOiIltGumRiYeN7qmzWuX5leOVMwnN2CIpsjo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);